version: "3"
services:
  database:
    image: postgres:latest
    # image: mysql:latest
    # command: mysqld --default-authentication-plugin=mysql_native_password
    # environment:
    # MYSQL_USER: root
    # MYSQL_ROOT_PASSWORD: password
    volumes:
      # - ./aircon_controller/db/mysql_data:/var/lib/mysql
      - ../remote_controller/db/postgresql_data:/var/lib/postgresql/data
  web:
    build:
      context: ../remote_controller
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../remote_controller:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - database
